Repository jokk-itu/PythonKindergarten, pull requests merged in 2021-03, with the labels that each got.

#44 Topic/userresponsive
  .vagrant/machines/production/digital_ocean/vagrant_cwd
  MiniTwitApi/.idea/config/applicationhost.config
  MiniTwitApi/Client/Models/Abstract/IMessageModel.cs
  MiniTwitApi/Client/Models/MessageModel.cs
  MiniTwitApi/Client/Pages/Index.razor
  MiniTwitApi/Client/Pages/Messages.razor
  MiniTwitApi/Client/Pages/Old_Timeline.razor
  MiniTwitApi/Client/Pages/PublicTimeline.razor
  MiniTwitApi/Client/Pages/timeline temp
  MiniTwitApi/Client/ViewModels/Abstract/IMessageViewModel.cs
  MiniTwitApi/Client/ViewModels/MessageViewModel.cs
  MiniTwitApi/Server/Controllers/MessageController.cs
  MiniTwitApi/Server/Controllers/MiniTwitController.cs
  MiniTwitApi/Server/Controllers/MiscController.cs
  MiniTwitApi/Server/Repositories/Abstract/IMessageRepository.cs
  MiniTwitApi/Server/Repositories/FollowerRepository.cs
  MiniTwitApi/Server/Repositories/MessageRepository.cs
  MiniTwitApi/Server/Startup.cs
  MiniTwitApi/Shared/Models/MessageModels/MessageDTO.cs
  MiniTwitApi/Shared/Models/UserModels/UserDTO.cs
  MiniTwitApi/Shared/Repositories/Abstractions/IMiniTwitRepository.cs
  MiniTwitApi/Shared/Repositories/MiniTwitRepository.cs
Labels: enhancement

#52 Topic/cookie login
  MiniTwitApi.Tests/Repositories/UserRepositoryTests.cs
  MiniTwitApi/Client/App.razor
  MiniTwitApi/Client/CustomAuthenticationStateProvider.cs
  MiniTwitApi/Client/MiniTwitApi.Client.csproj
  MiniTwitApi/Client/Models/Abstract/IUserModel.cs
  MiniTwitApi/Client/Models/FollowModel.cs
  MiniTwitApi/Client/Models/UserModel.cs
  MiniTwitApi/Client/Pages/Error.razor
  MiniTwitApi/Client/Pages/Login.razor
  MiniTwitApi/Client/Pages/Messages.razor
  MiniTwitApi/Client/Pages/MyTimeline.razor
  MiniTwitApi/Client/Pages/Register.razor
  MiniTwitApi/Client/Pages/UserTimeline.razor
  MiniTwitApi/Client/Program.cs
  MiniTwitApi/Client/Shared/NavMenu.razor
  MiniTwitApi/Client/ViewModels/Abstract/AbstractTimelineViewModel.cs
  MiniTwitApi/Client/ViewModels/Abstract/ILoginViewModel.cs
  MiniTwitApi/Client/ViewModels/Abstract/IMessageViewModel.cs
  MiniTwitApi/Client/ViewModels/Abstract/IMyTimelineViewModel.cs
  MiniTwitApi/Client/ViewModels/Abstract/IRegisterViewModel.cs
  MiniTwitApi/Client/ViewModels/Abstract/IUserTimelineViewModel.cs
  MiniTwitApi/Client/ViewModels/Abstract/IViewModel.cs
  MiniTwitApi/Client/ViewModels/MyTimelineViewModel.cs
  MiniTwitApi/Client/ViewModels/UserTimelineViewModel.cs
  MiniTwitApi/Client/_Imports.razor
  MiniTwitApi/Client/wwwroot/index.html
  MiniTwitApi/Server/Controllers/UserController.cs
  MiniTwitApi/Server/Startup.cs
Labels: enhancement, refactoring

#53 Implemented a redesign of MiniTwit
  MiniTwitApi/Client/Pages/Messages.razor
  MiniTwitApi/Client/Pages/MyTimeline.razor
  MiniTwitApi/Client/Pages/PublicTimeline.razor
  MiniTwitApi/Client/Pages/Register.razor
  MiniTwitApi/Client/Pages/UserTimeline.razor
  MiniTwitApi/Client/Shared/MainLayout.razor
  MiniTwitApi/Client/Shared/MainLayout.razor.css
  MiniTwitApi/Client/Shared/NavMenu.razor
  MiniTwitApi/Client/Shared/NavMenu.razor.css
  MiniTwitApi/Client/wwwroot/css/app.css
  MiniTwitApi/Client/wwwroot/index.html
Labels: enhancement

#67 Timestamp fix and color fix
  MiniTwitApi/Client/Pages/Messages.razor
  MiniTwitApi/Client/wwwroot/css/app.css
Labels: bug, enhancement

#69 Add redirect for logout.
  MiniTwitApi/Client/Shared/NavMenu.razor
  MiniTwitApi/Server/Controllers/UserController.cs
Labels: enhancement

#78 Added flag tool/profanity filter
  .ionide/symbolCache.db
  MiniTwitApi.Tests/ProfanityFilterTests.cs
  MiniTwitApi/Client/Pages/Messages.razor
  MiniTwitApi/Client/wwwroot/css/app.css
  MiniTwitApi/Server/Controllers/MessageController.cs
  MiniTwitApi/Server/ProfanityFilter.cs
  images/MiniTwit-deps.png
  images/Screenshot from 2021-03-07 13-43-46.png
  images/Screenshot from 2021-03-07 13-46-46.png
  old/Makefile
  old/control.sh
  old/control.sh.save
  old/flag_tool
  old/flag_tool.c
  old/minitwit.py
  old/minitwit_simulator.py
  old/minitwit_tests.py
  old/out.log
  old/schema.sql
Labels: enhancement
